from pathlib import Path

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
ORANGE = (255, 165, 0)
SILVER = (192, 192, 192)
MUTED_RED = (170, 70, 70)
COSMIC_PURPLE = (78, 30, 100)
VIBRANT_CYAN = (50, 205, 230)
NEBULA_PINK = (255, 69, 200)
GREEN = (0, 255, 0)
DARK_GREY = (50, 50, 50)
TRANSPARENT = (0, 0, 0, 0)

# Game window settings
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
FPS = 90

SOFT_BOUND_TOP = 0
SOFT_BOUND_BOTTOM = SCREEN_HEIGHT     
SOFT_BOUND_LEFT = 0
SOFT_BOUND_RIGHT = SCREEN_WIDTH

HARD_BOUND_PADDING = 42
HARD_BOUND_TOP = SOFT_BOUND_TOP - HARD_BOUND_PADDING
HARD_BOUND_BOTTOM = SOFT_BOUND_BOTTOM + HARD_BOUND_PADDING
HARD_BOUND_LEFT = SOFT_BOUND_LEFT - HARD_BOUND_PADDING
HARD_BOUND_RIGHT = SOFT_BOUND_RIGHT + HARD_BOUND_PADDING

BKGD_COLOR = BLACK

# GUI
HUD_HEIGHT = 100 # For score/info

# Environment
GROUND_HEIGHT = 800

# Menu 
MENU_COOLDOWN_MS = 200

# Motions
MAX_SPEED = 300

# Map

HEIGHT_CONSTANT = 100

# Paths

DIR_BASE = Path(__file__).resolve().parent
DIR_ASSETS = DIR_BASE / "assets"
DIR_CHARACTER = DIR_ASSETS / "character"

if __name__ == "__main__":
    # code that only runs when this file is executed directly
    print()
