# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
ORANGE = (255, 165, 0)
SILVER = (192, 192, 192)
MUTED_RED = (170, 70, 70)
COSMIC_PURPLE = (78, 30, 100)
VIBRANT_CYAN = (50, 205, 230)
NEBULA_PINK = (255, 69, 200)
GREEN = (0, 255, 0)
DARK_GREY = (50, 50, 50)
TRANSPARENT = (0, 0, 0, 0)

# Game window settings
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
FPS = 90
HUD_HEIGHT = 100 # For score/info

# Game Setup
BKGD_COLOR = BLACK
SHIP_X = SCREEN_WIDTH // 2
SHIP_Y = SCREEN_HEIGHT // 2

SOFT_BOUNDARY_TOP = 0
SOFT_BOUNDARY_BOTTOM = SCREEN_HEIGHT - HUD_HEIGHT     
SOFT_BOUNDARY_LEFT = 0
SOFT_BOUNDARY_RIGHT = SCREEN_WIDTH

HARD_BOUNDARY_PADDING = 42
HARD_BOUNDARY_TOP = SOFT_BOUNDARY_TOP - HARD_BOUNDARY_PADDING
HARD_BOUNDARY_BOTTOM = SOFT_BOUNDARY_BOTTOM + HARD_BOUNDARY_PADDING
HARD_BOUNDARY_LEFT = SOFT_BOUNDARY_LEFT - HARD_BOUNDARY_PADDING
HARD_BOUNDARY_RIGHT = SOFT_BOUNDARY_RIGHT + HARD_BOUNDARY_PADDING

# Menu 

PARTICLE_SPEED = 200
PARTICLE_GENERATION = 300 # Timelapse between pixels generated (msec)
MENU_COOLDOWN_MS = 200

# Motions
ROTATION_SPEED = 175
THRUST_POWER = 300
BRAKE_POWER = 300
DRAG = .8
MAX_SPEED = 300

BULLET_OFFSET = 16
BULLET_SPEED = 320
BULLET_MAX_DISTANCE = 500
FIRE_DELAY_MS = 100

ASTROID_ROTATION_SPEED = 80
ASTROID_MOVEMENT_SPEED = 10
ASTROID_SPAWN_RATE_START = 500 # Initial spawn interval in ms
ASTROID_SPAWN_RATE_MIN = 1 # Fastest spawn interval (hard cap)
ASTROID_SPAWN_ACCEL = 0.01 # Decrease per second (ms/sec)

# Forcefield

FORCEFIELD_HEALTH = 5

# Explosions

EXPLOSION_SPEED = 0.50
NUM_RINGS = 10
EXPLOSION_DURATION = 4

# Paths

DIR_ASSETS = "assets/"